### ISSUE TITLE
Gulp: Add a concat task for vendors

### ISSUE THREAD

**Issue by JonasDeGeest** [getchopstick/chopstick-boilerplate#103]

**Comment by xavez** [comment]
@JonasDeGeest do you think we need this in the boilerplate? I think, since we’re only using jQuery, modernizr and respond.js, no concatenation is needed:

- jQuery goes in the body and prefers a CDN version over a local version for caching
- modernizr goes in the head
- respond.js should be removed in the near future (I will make a separate issue for this)

What do you think?

**Comment by JonasDeGeest** [comment]
Maybe not. Vendors tend to be project specific. Having a task that combines those vendors and optionally minifying them could come in handy. I don't see it as a must, but I see it using it myself frequently.

**Comment by xavez** [comment]
Cool. Have you done it on other projects? If so, maybe we can reuse the code?

**Comment by JonasDeGeest** [comment]
Sure, I can make a pull request.

**Comment by xavez** [comment]
That would be most excellent!

**Comment by xavez** [comment]
@JonasDeGeest any progress on that PR?

**Comment by xavez** [comment]
Closing, issue is stale.
