### ISSUE TITLE
Use atomic design naming standard for _includes prefixes

### ISSUE THREAD

**Issue by Dietr** [getchopstick/chopstick-boilerplate#128]
[Atomic design](http://bradfrost.com/blog/post/atomic-web-design/) provides a clear way to name partials.

We could upgrade the current prefixes: `component`, `element` and `object` to `atom`, `molecule` and `organism`.

**Comment by xavez** [comment]
I personally think `component`, `element` and `object` are just as meaningful as `atom`, `molecule` and `organism`. The latter being even a bit more vague / theoretical in my opinion.

**Comment by Dietr** [comment]
The goal is to create a clear hierarchy or category for includes. Component and object could be perceived as synonyms and have no clear hierarchy. It's also confusing because the naming of includes is similar to how we name our `scss` layers. 

I'm not necessarily looking for more meaning but a better hierarchy and more clarity. The current naming does not provide this.

Atomic design is one way but we could also invent our own?
- Small parts like buttons, links, etc > atoms or elements
- Grouped interface elements, standalone features > organisms or components
- Partials which are only functional and not visual (e.g. head, javascript, ...) > generic
- Example snippets only used in the styleguide > styleguide or demo (currently a mix of elements, trumps, components)

**Comment by xavez** [comment]
I agree that the difference between Component and Object can be confusing.

I tried to come up with a good practical reason for why we should separate them, but I couldn’t. Why is a responsive table an object, and not a component? In theory, I understand there is a difference, in practice, I could go looking for a responsive table in the components and for a button in the objects.

I am more and more inclined to get rid of objects, make some objects components, and some objects a utility:

- `.o-grid`: utility `.u-grid` and `.u-container`
- `.o-flexbox`: utility `.u-flexbox` . . .
- `.o-list`: utility `.u-naked-list` and `.u-horizontal-list`
- `.o-media-embed`: component `.u-media-embed`
- `.o-media`: component `.c-media`
- `.o-table-responsive`: utility `.c-table-responsive`

Which would be a simplification in practice, if only because you have one less place to go looking for something.

**Comment by Dietr** [comment]
I think we're talking about different things 😄 

This issue is about the naming of our Jekyll includes (html) so not the _scss includes or the ITCSS architecture we are using. I think the fact that we are using similar naming causes this confusion.

As for the original issue. I posted a related issue #134 which might fix my confusion of includes used for the styleguide and includes used for the actual site or prototype. Which would mean the files in the _includes folder does not really need prefixes if you don't want them. Or you could use what you prefer.

I don't agree on the confusion between object/component/utilities. This seems very clear to me.
- objects: a repeating visual pattern with only structure and no skin
- components: specific designed/skinned parts of a website/UI
- utilities: overrides, should only do one thing (e.g. width, display, ...)

As we are following the ITCSS structure it also seems logical to keep this naming convention.
