### ISSUE TITLE
Uglify?

### ISSUE THREAD

**Issue by TimonRiemslagh** [getchopstick/chopstick-boilerplate#147]
Do we include uglify in chopstick?

Chopstick being a prototyping tool, do we need to uglify the javascript?

I say we create a task that handles the uglify, if the Themer/Webdeveloper doing the integration needs the javascript the task can be disabled.

What do you guys think?

**Comment by fspin** [comment]
I thought that the uglify was already included. But, no.. it isn't. 

I would rather include it, as an optional task: while developing/debugging seeing the code (not uglified) in the browser's inspector, is quite important to me. 

So, I would run the uglify task just before going to production.

Agree with the idea of including it. But a better approach (to me) will be making this task as opt-it, rather than opt-out.

**Comment by TimonRiemslagh** [comment]
I fear that if we include the task as optional, someone needs to think about activating it before going to production and this will be forgotten.

**Comment by jessedobbelaere** [comment]
If we add good sourcemaps support for debugging, we perhaps don't need to make uglifying optional?

**Comment by TimonRiemslagh** [comment]
I like that idea! Let's set up a branch with the uglify/sourcemap and see if it is usable.
