### ISSUE TITLE
Add configurable javascript patterns

### ISSUE THREAD

**Issue by Dietr** [getchopstick/chopstick-boilerplate#70]

**Comment by xavez** [comment]
Can you specify a bit more what is needed? The issue is unclear to me.

**Comment by Dietr** [comment]
This is currently being developed in the [modularizing-javascript](https://github.com/getchopstick/chopstick-boilerplate/tree/modularizing-javascript) branch.

@JonathanDcstr is working on this but I think it contains the following tasks:

- [ ] Change javascript structure to module pattern
- [ ] Rewrite mobilenav to a more flexible toggle script
- [ ] Add common used javascript components, a modal for example (although maybe this should be written as Chopstick plugins?)

**Comment by xavez** [comment]
Is this still actively worked on @JonathanDcstr ?

**Comment by TimonRiemslagh** [comment]
How can we make the javascript of chopstick modular?

The ideal situation would be to include the modules you need and nothing more. All the other javascript would not be included. 

We investigated 2 different ways to make the javascript modular:

1. Create modules through IIFE.

I think the downside of this method is that we need to include all the javascript all the time, if you are working with a website with tons of javascript you might not need all the javascript all the time.

2. Create require (requirejs) modules and include them when needed.

The idea is to include some standard modules, e.g. modal and toggle, and make it possible to download more modules when needed.

What do you guys think of those 2 methods, pros/cons?
Are there other methods that we need to investigate?
Any questions about the methods, shoot!

**Comment by xavez** [comment]
@TimonRiemslagh I think we should keep this as simple as possible for novice users so that it requires little or no set up. How would adding `requirejs` make things simpler or better? (genuine question). Do you have an example of how it would work?

**Comment by TimonRiemslagh** [comment]
@xavez I was researching the modular way to write javascript and I maybe went a little too far with the Requirejs. Requirejs would not make it easier for the designer, because he would have to define the require modules.

After a quick thinking session and discussing it with some designers/developers I came up with the following situation:

We write the chopstick JS (preferably all the javascript) in such a modular manner that the entire module is configurable with html data attributes (I don't know if this is entirely possible, especially for the more complex modules). 

Now the designer can just download the module (plugin), reference it in his website or prototype and define the html element with all the attributes. There will be enough documentation needed to specify the possible attributes. For this process I was thinking about npm, create a node module, so that the designer can define all the modules it need with a package.json file, and we can keep track of the version of the modules as well.

This situation adds no complexity for the designer, what are your thoughts about this?

Kind Regards,
Timon

**Comment by xavez** [comment]
That seems like an excellent plan, and a very exciting future for the JS in Chopstick @TimonRiemslagh!

**Comment by jessedobbelaere** [comment]
In regard of future of JS in Chopstick, any plans to also start supporting ES2015? While writing JS, cool features such as ES6 modules, let instead of var, arrow functions, spread operator, template strings, promises&generators, ... would be great to have! We could add babel in Gulp or add Webpack support with babel. In the end, gulp/webpack compiles the ES6 code to minified ES5 JS code anyway. 

It would make Chopstick stay cutting-edge for frontend developers so we can use al the latest cool features, while making it easy to use for designers with @TimonRiemslagh his proposal.

**Comment by TimonRiemslagh** [comment]
@jessedobbelaere I think if we want to make the Chopstick JS modular and cutting-edge there is no point in not supporting ES2015, the extra functionality like classes and inheritance will make the modules way better. I think using Babel as a gulp task to compile it to ES5 sounds like a good plan. We are already using gulp to minify our JS anyway. Now all I need to do is make a plan and get budget to do this :).

**Comment by xavez** [comment]
Closing this issue as it has become stale (>14days of inactivity). Please submit a Pull Request when there is something actionable.
